In [1]:
import numpy as np

In [2]:
#Create an array
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Loading the saved array
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [7]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr)

In [8]:
archive_array = np.load('two_arrays.npz')

In [9]:
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [12]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])