In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
# Binary functions
A = np.random.randn(10)

In [7]:
A

array([-3.15928695,  1.27922809, -0.53188278, -1.26670884,  1.06461925,
        0.83878434,  0.67655832,  0.7372298 , -0.24585254, -0.13895251])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-0.44622263,  0.75337789,  1.20445145,  0.65981431, -1.61755766,
       -1.78472113, -0.37406947, -0.85496204,  1.31578852,  2.44011397])

In [10]:
np.add(A,B)

array([-3.60550959,  2.03260599,  0.67256867, -0.60689453, -0.55293841,
       -0.94593679,  0.30248886, -0.11773224,  1.06993598,  2.30116145])

In [11]:
np.maximum(A,B)

array([-0.44622263,  1.27922809,  1.20445145,  0.65981431,  1.06461925,
        0.83878434,  0.67655832,  0.7372298 ,  1.31578852,  2.44011397])

In [12]:
np.minimum(A,B)

array([-3.15928695,  0.75337789, -0.53188278, -1.26670884, -1.61755766,
       -1.78472113, -0.37406947, -0.85496204, -0.24585254, -0.13895251])