Second part of different functions available within numpy arrays

In [1]:
from __future__ import division

In [2]:
import numpy as np
arr1 = np.array([[1,2,3],[8,9,10]])

In [3]:
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [4]:
arr1 * arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [5]:
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
arr1 * 2

array([[ 2,  4,  6],
       [16, 18, 20]])

In [8]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])