In [1]:
# Numpy arrays

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4]

In [4]:
my_array = np.array(my_list)

In [5]:
my_array

array([1, 2, 3, 4])

In [7]:
my_list2 = [11,22,33,44]

In [9]:
my_lists = [my_list, my_list2]

In [10]:
my_array2 = np.array(my_lists)

In [11]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.shape

(2, 4)

In [13]:
my_array2.dtype

dtype('int64')

In [14]:
np.zeros(5, dtype='float64')

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
np.arange(6).reshape([2,3])

array([[0, 1, 2],
       [3, 4, 5]])